import { Button } from "std-widgets.slint";

global AppColors {
    out property <color> background: #2c3e50;
    out property <color> primary: #3498db;
    out property <color> success: #27ae60;
    out property <color> danger: #e74c3c;
    out property <color> text-primary: #ecf0f1;
    out property <color> text-secondary: #bdc3c7;
}

export component AppWindow inherits Window {
    title: "TaskBoard — Slint Template";
    background: AppColors.background;
    icon: @image-url("./icon.png");
    callback quit();
    VerticalLayout {
        padding: 16px;
        spacing: 12px;
        Text {
            text: "Olá, Slint + Rust!"; 
            font-size: 22px;
            color: AppColors.text-primary;
        }

        Text {
            text: "Este é o seu template base."; 
            color: AppColors.text-secondary;
        }

        HorizontalLayout {
            spacing: 8px;
            Button {
                text: "OK";
                clicked => {
                    root.title = "Clicou em OK";
                }
            }

            Button {
                text: "Sair";
                clicked => {
                    root.quit();
                }
            }
        }
    }
}
