import { Button } from "std-widgets.slint";
import { Light, Dark, Theme, StatusColors, StatusLight, StatusDark } from "theme.slint";
import { ToggleTheme } from "components/toggle-theme.slint";
import { Main } from "pages/main.slint";

export component AppWindow inherits Window {
    title: "TaskBoard — Slint Template";
    in-out property <string> current_theme: "light";
    private property <Theme> theme: current_theme == "light" ? Light.theme : Dark.theme;
    private property <StatusColors> status: current_theme == "light" ? StatusLight.colors : StatusDark.colors;
    background: theme.bg;
    icon: @image-url("../build/icon.png");
    callback toggle_theme();
    Main {
        theme: root.theme;
        current_theme: root.current_theme;
        toggle_theme => {
            root.toggle_theme();
        }
    }
}
